# Generated by Django 3.0.5 on 2020-04-03 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MatchFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Message text')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('genders', models.CharField(choices=[('M', 'Мужчина'), ('FM', 'Женщина'), ('UNKW', 'Неизвестно')], default='UNKW', max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('about_me', models.TextField(max_length=300)),
                ('avatar', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(check=models.Q(age__gte=18), name='age_gte_18'),
        ),
        migrations.AddField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dating_app.Dialog', verbose_name='Dialog'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='matchfriend',
            name='current_user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='dating_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='matchfriend',
            name='users',
            field=models.ManyToManyField(to='dating_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='interests',
            name='interests',
            field=models.ManyToManyField(blank=True, to='dating_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dialog opponent'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfDialogs', to=settings.AUTH_USER_MODEL, verbose_name='Dialog owner'),
        ),
    ]
