# Generated by Django 3.0.5 on 2020-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skip_ids',
            field=models.ManyToManyField(blank=True, to='dating_app.UserProfile'),
        ),
    ]
