# Generated by Django 3.0.5 on 2020-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0002_userprofile_skip_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='like_ids',
            field=models.ManyToManyField(blank=True, related_name='like_id', to='dating_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender_pref',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('Неизвестно', 'Неизвестно')], default='Неизвестно', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genders',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('Неизвестно', 'Неизвестно')], default='Неизвестно', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skip_ids',
            field=models.ManyToManyField(blank=True, related_name='skip_id', to='dating_app.UserProfile'),
        ),
    ]
