# Generated by Django 3.0.5 on 2020-04-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0003_auto_20200414_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
