# Generated by Django 3.0.5 on 2020-04-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0004_delete_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='dialog',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
